let productWood = [
  {
    id: "1",
    title: "Door",
    name: "iron door",
    img: "../images/door1.png",
    mark: "4.5",
    price: "100",
  },
  {
    id: "2",
    title: "Door",
    name: "double door",
    img: "../images/door22.jfif",
    mark: "5",
    price: "150",
  },
  {
    id: "3",
    title: "Door",
    name: "Office door",
    img: "../images/door333.jpg",
    mark: "5",
    price: "120",
  },
  {
    id: "4",
    title: "Door",
    name: "Four windows",
    img: "../images/door4.jfif",
    mark: "4",
    price: "150",
  },
  {
    id: "5",
    title: "Door",
    name: "Four windows",
    img: "../images/door5.jfif",
    mark: "3.5",
    price: "80",
  },
  {
    id: "6",
    title: "Door",
    name: "MDF",
    img: "../images/door66.jpg",
    mark: "3",
    price: "50",
  },

  // wood

  {
    id: "7",
    title: "Wood",
    name: "California wood",
    img: "../images/wood11.png",
    mark: "5",
    price: "250",
  },
  {
    id: "8",
    title: "Wood",
    name: "roof wood",
    img: "../images/wood22.jfif",
    mark: "4",
    price: "150",
  },
  {
    id: "9",
    title: "Wood",
    name: "Main wood",
    img: "../images/wood33.jfif",
    mark: "3",
    price: "50",
  },
  {
    id: "10",
    title: "Wood",
    name: "Floor is wooden",
    img: "../images/wood4.jfif",
    mark: "4.5",
    price: "100",
  },
  {
    id: "11",
    title: "Wood",
    name: "White wood",
    img: "../images/wood5.jpg",
    mark: "3.5",
    price: "80",
  },
  {
    id: "11",
    title: "Wood",
    name: "Superior wood",
    img: "../images/wood6.jfif",
    mark: "3",
    price: "50",
  },

  //   tools

  {
    id: "12",
    title: "Tools",
    name: "Drill",
    img: "../images/drel.png",
    mark: "5",
    price: "150",
  },
  {
    id: "13",
    title: "Tools",
    name: "Hummer",
    img: "../images/hummer.png",
    mark: "4",
    price: "30",
  },
  {
    id: "14",
    title: "Tools",
    name: "Circul saw",
    img: "../images/circul.png",
    mark: "5",
    price: "200",
  },
  {
    id: "15",
    title: "Tools",
    name: "Polisher",
    img: "../images/polisher.png",
    mark: "4",
    price: "150",
  },
  {
    id: "16",
    title: "Tools",
    name: "Jack hummer",
    img: "../images/jack.png",
    mark: "5",
    price: "200",
  },
  //   paper
  {
    id: "17",
    title: "Wall-paper",
    name: "Grey paper",
    img: "../images/paper1.jpg",
    mark: "4.5",
    price: "180",
  },
  {
    id: "18",
    title: "Wall-paper",
    name: "Black paper",
    img: "../images/paper2.jfif",
    mark: "5",
    price: "200",
  },
  {
    id: "19",
    title: "Wall-paper",
    name: "Light paper",
    img: "../images/paper3.jfif",
    mark: "5",
    price: "200",
  },
  {
    id: "20",
    title: "Wall-paper",
    name: "White paper",
    img: "../images/paper4.jfif",
    mark: "4",
    price: "100",
  },
  {
    id: "21",
    title: "Wall-paper",
    name: "Orange paper",
    img: "../images/paper5.jfif",
    mark: "3",
    price: "20",
  },
  {
    id: "22",
    title: "Wall-paper",
    name: "Brown paper",
    img: "../images/paper6.jfif",
    mark: "5",
    price: "250",
  },
  //   pipe
  {
    id: "23",
    title: "Pipe",
    name: "Silver pipe",
    img: "../images/pipe1.png",
    mark: "4",
    price: "20",
  },
  {
    id: "24",
    title: "Pipe",
    name: "Bit pipe",
    img: "../images/pipe2.png",
    mark: "5",
    price: "100",
  },
  {
    id: "25",
    title: "Pipe",
    name: "Water pipe",
    img: "../images/pipe3.png",
    mark: "4.5",
    price: "50",
  },
  {
    id: "26",
    title: "Pipe",
    name: "Pipe",
    img: "../images/pipe4.png",
    mark: "4",
    price: "150",
  },
  {
    id: "27",
    title: "Pipe",
    name: "Black pipe",
    img: "../images/pipe5.png",
    mark: "4",
    price: "150",
  },
  {
    id: "28",
    title: "Pipe",
    name: "Iron pipe",
    img: "../images/pipe6.png",
    mark: "4",
    price: "150",
  },
  // build
  {
    id: "29",
    title: "Build",
    name: "Roof",
    img: "../images/shifer1.png",
    mark: "4",
    price: "150",
  },
  {
    id: "30",
    title: "Build",
    name: "Brick",
    img: "../images/brick.png",
    mark: "4",
    price: "10",
  },
  {
    id: "31",
    title: "Build",
    name: "Cement",
    img: "../images/sement.jpg",
    mark: "4",
    price: "100",
  },
  {
    id: "32",
    title: "Build",
    name: "Iron",
    img: "../images/iron1.jfif",
    mark: "4",
    price: "100",
  },
];
